name: "build"
on: [push, pull_request]
env:
  TRIVY_VERSION: 0.45.0
  COPA_VERSION: 0.4.0
  BUILDKIT_VERSION: 0.11.2
permissions: read-all
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Install Trivy
        run: |
            curl -fsSL -o trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v${{ env.TRIVY_VERSION }}/trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.tar.gz
            tar -zxvf trivy.tar.gz
            cp trivy /usr/local/bin/

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull docker.io/library/nginx:1.21.6
        run: docker pull docker.io/library/nginx:1.21.6

      - name: Install Copa
        run: |
            curl --retry 5 -fsSL -o copa.tar.gz https://github.com/project-copacetic/copacetic/releases/download/v${{ env.COPA_VERSION }}/copa_${{ env.COPA_VERSION }}_linux_amd64.tar.gz
            tar -zxvf copa.tar.gz 
            cp copa /usr/local/bin/

      - name: Bats Test
        run: |
          docker run --net=host --detach --rm --privileged -p 127.0.0.1:8888:8888 --name buildkitd --entrypoint buildkitd moby/buildkit:v${{ env.BUILDKIT_VERSION }} --addr tcp://0.0.0.0:8888
          docker build --build-arg copa_version=${{ env.COPA_VERSION }} -t copa-action .
          cd ${{ github.workspace }}/test
          docker run --net=host \
            --mount=type=bind,source=$(pwd)/data,target=/data \
            --mount=type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
            --mount=type=bind,source=$GITHUB_OUTPUT,target=$GITHUB_OUTPUT -e GITHUB_OUTPUT \
            --name=copa-action \
            copa-action 'docker.io/library/nginx:1.21.6' 'nginx.1.21.6.json' '1.21.6-patched'
          docker images
          bats --print-output-on-failure ./test.bats